import { Hero } from "./models/hero.model"

export const HEROES: Hero[] = [
  {
    id: 1,
    name: 'Super Man',
    gender: 'Hombre',
    height: 1.90,
    weight: 120,
    powers: ['Fuerza', 'Volar', 'Velocidad', 'Visión calorica', 'Visión de rayos X'],
    weakness: 'Criptonita',
    weapons: null,
    image: 'https://www.cinemascomics.com/wp-content/uploads/2023/08/Superman-Legacy.jpg'
  },
  {
    'id': 2,
    'name': 'Batman',
    'gender': 'Hombre',
    'height': 1.89,
    'weight': 105,
    'powers': [''],
    'weakness': '',
    'weapons': null,
    'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmPFUNxzqxFwl6pK_qb8jMMLLTicqpRR7ADQ&usqp=CAU',
  },
  {
    'id': 3,
    'name': 'Mujer Maravilla',
    'gender': 'Mujer',
    'height': 73,
    'weight': 1.79,
    'powers': ['Fuerza'],
    'weakness': '',
    'weapons': ['Espada', 'Escudo', 'Lazo de la verdad'],
    'image': 'https://www.akiracomics.com/imagenes/poridentidad?identidad=23bee68b-e5bb-40ad-bdde-8cbaf364ea3a&ancho=850&alto=',
  },
  // {
  //   'id': 2,
  //   'name': '',
  //   'gender': 'Hombre',
  //   'height': 34,
  //   'weight': 56,
  //   'powers': [''],
  //   'weakness': '',
  //   'weapons': null,
  //   'image': '',
  // },
  // {
  //   'id': 2,
  //   'name': '',
  //   'gender': 'Hombre',
  //   'height': 34,
  //   'weight': 56,
  //   'powers': [''],
  //   'weakness': '',
  //   'weapons': null,
  //   'image': '',
  // },
]
